apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: employedb
  name: devops-test
  labels:
    k8s-app: 
spec:
  selector:
    matchLabels:
      name: employedb-pod
  template:
    metadata:
      labels:
        name: employedb
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: employedb
        image: payalsasmal/empdb:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
