pipeline {
	 environment {
	    registry = "payalsasmal/empdb"
	    registryCredential = 'dockerhub'
	    app = ''
	    PROJECT_ID = 'rising-webbing-276809'
            CLUSTER_NAME = 'docker-image'
            LOCATION = 'us-central1-c'
            CREDENTIALS_ID = 'gke'

  	}
	agent any
	stages {
	        stage('Clone Repository') {
	        steps {
	            checkout scm
	            }
	        }
	   stage('Build Docker Image') {
	        steps {
		    script {
			     app = docker.build("payalsasmal/empdb:${env.BUILD_ID}")
			     app.inside {
				sh 'echo $(curl localhost:8888)'
			     }
		    }
	        }
	   }
	   
	   stage('Push Docker image') {
	        steps {
                   script {
                        docker.withRegistry( '', registryCredential ) {
                           app.push("latest")
			   app.push("${env.BUILD_ID}")	
                        }
	               }
	   
	        }
	   }

	   stage('Deploy to K8S') {
	        steps{
			sh "sed -i 's/empdb:latest/empdb:${env.BUILD_ID}/g' daemonset.yaml"
			step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, location: env.LOCATION, manifestPattern: 'daemonset.yaml',
			credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])
            	}



	    }


    }
}